name: emeandeme
description: "La boda de las dos Eme más impresionantes de la historia María Luisa y Manuel. La Magnolia y el Magnolio. María y el inculto musical. La bella y el Iteuvetero. Ahora en formato página web para organizar un poco el percal"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # flutter_inappwebview: ^6.0.0
  webviewx_plus: ^0.5.0
  url_launcher: 6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: 2.3.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/hoteles/
  fonts:
    - family: Belleza
      fonts:
        - asset: assets/fonts/Belleza-Regular.ttf
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Italic-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/NotoSerif-VariableFont_wdth,wght.ttf
    - family: Now
      fonts:
        - asset: assets/fonts/now/Now-Black.otf
        - asset: assets/fonts/now/Now-Bold.otf
        - asset: assets/fonts/now/Now-Light.otf
        - asset: assets/fonts/now/Now-Medium.otf
        - asset: assets/fonts/now/Now-Regular.otf
        - asset: assets/fonts/now/Now-Thin.otf
        - asset: assets/fonts/now/NowAlt-Black.otf
        - asset: assets/fonts/now/NowAlt-Bold.otf
        - asset: assets/fonts/now/NowAlt-Light.otf
        - asset: assets/fonts/now/NowAlt-Medium.otf
        - asset: assets/fonts/now/NowAlt-Regular.otf
        - asset: assets/fonts/now/NowAlt-Thin.otf
